### ISSUE TITLE
argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by hannesdelbeke** [plugget/plugget-qt-maya-plugin#7]
py_pip has a Path instead of string in target or interpreter path set

```
PackagesMeta(pyblish not installed)
app_path C:\Users\HANNES~1.DEB\AppData\Local\Temp\plugget\plugget-pkgs\maya
install requirements to target C:\Users\hannes.debelke\Documents\maya\2022\scripts
// root : cloning 'https://github.com/hannesdelbeke/pyblish-maya-plugin' to 'C:\Users\HANNES~1.DEB\AppData\Local\Temp\plugget\maya\a123951e\pyblish\1.0\pyblish' // 
// root : ['command to run other:', ['git', 'clone', '--depth', '1', '--progress', 'https://github.com/hannesdelbeke/pyblish-maya-plugin', 'C:\\Users\\HANNES~1.DEB\\AppData\\Local\\Temp\\plugget\\maya\\a123951e\\pyblish\\1.0\\pyblish']] // 
// root : command: '{command}' // 
requirements.txt found: 'C:\Users\HANNES~1.DEB\AppData\Local\Temp\plugget\maya\a123951e\pyblish\1.0\pyblish\requirements.txt'
requirements.txt found, installing:  C:\Users\HANNES~1.DEB\AppData\Local\Temp\plugget\maya\a123951e\pyblish\1.0\pyblish\requirements.txt
# Traceback (most recent call last):
#   File "C:/Users/hannes.debelke/Documents/maya/scripts\plugget_qt\__init__.py", line 107, in <lambda>
#     install_button.clicked.connect(lambda r=row: self.install_package(r))
#   File "C:/Users/hannes.debelke/Documents/maya/scripts\plugget_qt\__init__.py", line 114, in install_package
#     cmd.install(package_meta.package_name, version=version)
#   File "C:/Users/hannes.debelke/Documents/maya/scripts\plugget\commands\__init__.py", line 242, in install
#     package.install(enable=enable, **kwargs)
#   File "C:/Users/hannes.debelke/Documents/maya/scripts\plugget\data\package.py", line 353, in install
#     action.install(self, *args, force=force, **kwargs)
#   File "C:/Users/hannes.debelke/Documents/maya/scripts\plugget\actions\_requirements.py", line 98, in install
#     py_pip.install(requirements=req_path, force=force, upgrade=True)
#   File "C:/Users/hannes.debelke/Documents/maya/scripts\py_pip\__init__.py", line 157, in install
#     process = install_process(package_name=package_name, target_path=target_path, force=force, upgrade=upgrade, requirements=requirements, options=options)
#   File "C:/Users/hannes.debelke/Documents/maya/scripts\py_pip\__init__.py", line 128, in install_process
#     return run_command_process(command)
#   File "C:/Users/hannes.debelke/Documents/maya/scripts\py_pip\__init__.py", line 31, in run_command_process
#     return subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=my_env)
#   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\subprocess.py", line 800, in __init__
#     restore_signals, start_new_session)
#   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\subprocess.py", line 1148, in _execute_child
#     args = list2cmdline(args)
#   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\subprocess.py", line 555, in list2cmdline
#     needquote = (" " in arg) or ("\t" in arg) or not arg
# TypeError: argument of type 'WindowsPath' is not iterable
```

**Comment by hannesdelbeke** [comment]
this was caused by maya pip isntall action setting pathlib path
